BEGIN TRANSACTION;
CREATE TABLE `sales` (
	`date`	TEXT NOT NULL,
	`batchNo`	INTEGER NOT NULL UNIQUE,
	`product`	TEXT NOT NULL,
	`quantity`	INTEGER NOT NULL,
	PRIMARY KEY(`batchNo`)
);
CREATE TABLE `inventory` (
	`date`	TEXT NOT NULL UNIQUE,
	`F`	INTEGER NOT NULL,
	`G`	INTEGER NOT NULL,
	`N`	INTEGER NOT NULL,
	`L`	INTEGER NOT NULL,
	PRIMARY KEY(`date`)
);
COMMIT;
